### PR TITLE
fix: Remap bindings to not conflict with terminal

### LINKED ISSUE #246: <CR> in insert mode submits the prompt instead of inserting a new line
When I hit `<CR>` in insert mode in the chat window, it submits.

The only other binding I have on `<CR>` for imap is nvim-cmp.

Peek 2024-03-28 13-44

### PR DESCRIPTION
**Pull request by deathbeam**
C-m is same as CR on a lot of terminals, remap to C-s

Closes #246

### CODE REVIEW

File: lua/CopilotChat/config.lua [hunk 1]
```diff
@@ -169,7 +169,7 @@ return {
     },
     submit_prompt = {
       normal = '<CR>',
-      insert = '<C-m>',
+      insert = '<C-s>',
```
Comment (jellydn) [inline lua/CopilotChat/config.lua:172]: Oh, I didn't get this error as my config is `'<C-Enter>'`.
